/**
 * VerifyAuditChain handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { verifyAuditChain } from "@agentfence/api-server/domains/audits/handlers";
import type { AuditsDDDDependencies } from "@agentfence/api-server/domains/audits";
import { createCreateVerifyChainRequest } from "@agentfence/factories/audits";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@agentfence/tests/shared";
import { AUDITS_USE_CASES } from "../__factories__/use-cases.js";

describe("VerifyAuditChain", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AuditsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AuditsDDDDependencies>(
      AUDITS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateVerifyChainRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeVerifyAuditChain, "execute").mockResolvedValue(useCaseResult);

    await verifyAuditChain(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeVerifyAuditChain.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
