/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace-adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./halt-ack-repository.ddb.js";
export * from "./marketplace-adapter-repository.ddb.js";
export * from "./partner-attestation-repository.ddb.js";
export * from "./halt-ack-repository.adapter.js";
export * from "./marketplace-repository.adapter.js";
export * from "./partner-attestation-repository.adapter.js";
