/**
 * PartnerAttestationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace-adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PartnerAttestationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PartnerAttestationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PartnerAttestationRepository,
} from "@agentfence/services/marketplace-adapters";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PartnerAttestationRepositoryDdb } from "./partner-attestation-repository.ddb.js";

/**
 * PartnerAttestationRepositoryAdapter
 *
 * Implements PartnerAttestationRepository port for infrastructure layer.
 */
export class PartnerAttestationRepositoryAdapter implements PartnerAttestationRepository {
  private readonly ddb: PartnerAttestationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PartnerAttestationRepositoryDdb(this.dynamoClient);
  }

  async verifyPartnerAttestation(input: Parameters<PartnerAttestationRepository['verifyPartnerAttestation']>[0]): Promise<Awaited<ReturnType<PartnerAttestationRepository['verifyPartnerAttestation']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.verifyPartnerAttestation(input);
  }
}
