/**
 * ListShadowAgentConflicts handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listShadowAgentConflicts } from "@agentfence/api-server/domains/agents/handlers";
import type { AgentsDDDDependencies } from "@agentfence/api-server/domains/agents";
import { createShadowConflict as createShadowConflictEntity } from "@agentfence/factories/agents";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@agentfence/tests/shared";
import { AGENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListShadowAgentConflicts", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AgentsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AgentsDDDDependencies>(
      AGENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createShadowConflictEntity({ orgId }),
      createShadowConflictEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListShadowAgentConflicts, "execute").mockResolvedValue(useCaseResult);

    await listShadowAgentConflicts(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListShadowAgentConflicts.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
