/**
 * AgentRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AgentRepository Port
 *
 * DDD: Application port for agentrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetAgentInput, GetAgentOutput, ListAgentsInput, ListAgentsOutput, RegisterAgentInput, RegisterAgentOutput, UpdateAgentInput, UpdateAgentOutput } from "../dto/agent.dto";
export interface AgentRepository {
  listAgents(input: ListAgentsInput): Promise<ListAgentsOutput>;
  registerAgent(input: RegisterAgentInput): Promise<RegisterAgentOutput>;
  getAgent(input: GetAgentInput): Promise<GetAgentOutput>;
  updateAgent(input: UpdateAgentInput): Promise<UpdateAgentOutput>;
}

export type { GetAgentInput, GetAgentOutput, ListAgentsInput, ListAgentsOutput, RegisterAgentInput, RegisterAgentOutput, UpdateAgentInput, UpdateAgentOutput } from "../dto/agent.dto";
