/**
 * RotateCredentialRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RotateCredentialRepository Port
 *
 * DDD: Application port for rotatecredentialrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RotateAgentCredentialsInput, RotateAgentCredentialsOutput } from "../dto/rotate-credential.dto";
export interface RotateCredentialRepository {
  rotateAgentCredentials(input: RotateAgentCredentialsInput): Promise<RotateAgentCredentialsOutput>;
}

export type { RotateAgentCredentialsInput, RotateAgentCredentialsOutput } from "../dto/rotate-credential.dto";
