/**
 * GetMarketplaceAdapter handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace-adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getMarketplaceAdapter } from "@agentfence/api-server/domains/marketplace-adapters/handlers";
import type { MarketplaceAdaptersDDDDependencies } from "@agentfence/api-server/domains/marketplace-adapters";
import { createMarketplaceAdapter as createMarketplaceAdapterEntity } from "@agentfence/factories/marketplace-adapters";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@agentfence/tests/shared";
import { MARKETPLACEADAPTERS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetMarketplaceAdapter", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: MarketplaceAdaptersDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<MarketplaceAdaptersDDDDependencies>(
      MARKETPLACEADAPTERS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createMarketplaceAdapterEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetMarketplaceAdapter, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { adapterId: entity.id };

    await getMarketplaceAdapter(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetMarketplaceAdapter.execute).toHaveBeenCalledWith(expect.objectContaining({ adapterId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { adapterId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetMarketplaceAdapter, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getMarketplaceAdapter(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
