/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the audits domain.
 * Use these factories in tests to create test data.
 */

export { createCreateEventRequest } from "./event/dto/create-event.dto.factory.js";
export { createCreateVerifyChainRequest } from "./verify-chain/dto/create-verify-chain.dto.factory.js";
