/**
 * SubmitAddOnPackage handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: add-ons
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { submitAddOnPackage } from "@agentfence/api-server/domains/add-ons/handlers";
import type { AddOnsDDDDependencies } from "@agentfence/api-server/domains/add-ons";
import { createCreateAddOnRequest } from "@agentfence/factories/add-ons";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@agentfence/tests/shared";
import { ADDONS_USE_CASES } from "../__factories__/use-cases.js";

describe("SubmitAddOnPackage", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AddOnsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AddOnsDDDDependencies>(
      ADDONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateAddOnRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeSubmitAddOnPackage, "execute").mockResolvedValue(useCaseResult);

    await submitAddOnPackage(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeSubmitAddOnPackage.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
