/**
 * AddOnRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: add-ons
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AddOnRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AddOnRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AddOnRepository,
} from "@agentfence/services/add-ons";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AddOnRepositoryDdb } from "./add-on-repository.ddb.js";

/**
 * AddOnRepositoryAdapter
 *
 * Implements AddOnRepository port for infrastructure layer.
 */
export class AddOnRepositoryAdapter implements AddOnRepository {
  private readonly ddb: AddOnRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AddOnRepositoryDdb(this.dynamoClient);
  }

  async listAddOnPackages(input: Parameters<AddOnRepository['listAddOnPackages']>[0]): Promise<Awaited<ReturnType<AddOnRepository['listAddOnPackages']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAddOnPackages(input);
  }

  async submitAddOnPackage(input: Parameters<AddOnRepository['submitAddOnPackage']>[0]): Promise<Awaited<ReturnType<AddOnRepository['submitAddOnPackage']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.submitAddOnPackage(input);
  }

  async getAddOnPackage(input: Parameters<AddOnRepository['getAddOnPackage']>[0]): Promise<Awaited<ReturnType<AddOnRepository['getAddOnPackage']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getAddOnPackage(input);
  }
}
