/**
 * Handlers for AddOn
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: add-ons
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AddOnsDomainModule } from "../dependencies/add-ons-ddd.dependencies.js";
import type { AddOnPackageCreateRequest } from "@agentfence/core/add-ons/types";
import type { GetAddOnPackageInput, ListAddOnPackagesInput, SubmitAddOnPackageInput } from "@agentfence/services/add-ons";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/add-ons
 * Operation: listAddOnPackages
 */
export async function listAddOnPackages(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AddOnsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListAddOnPackagesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.addOns.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/add-ons
 * Operation: submitAddOnPackage
 */
export async function submitAddOnPackage(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: AddOnPackageCreateRequest }>,
  reply: FastifyReply,
  deps: AddOnsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SubmitAddOnPackageInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.addOns.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/add-ons/{addOnId}
 * Operation: getAddOnPackage
 */
export async function getAddOnPackage(
  request: FastifyRequest<{ Params: { addOnId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AddOnsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetAddOnPackageInput = {
    addOnId: request.params.addOnId,
  };
  const result = await deps.useCases.addOns.get.execute(input);
  return reply.code(200).send(result);
}


