/**
 * Handlers for Approve
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: add-ons
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AddOnsDomainModule } from "../dependencies/add-ons-ddd.dependencies.js";
import type { AddOnAttestRequest } from "@agentfence/core/add-ons/types";
import type { ApproveAddOnPackageInput } from "@agentfence/services/add-ons";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/add-ons/{addOnId}/approve
 * Operation: approveAddOnPackage
 */
export async function approveAddOnPackage(
  request: FastifyRequest<{ Params: { addOnId: string }; Querystring: Record<string, string | string[] | undefined>; Body: AddOnAttestRequest }>,
  reply: FastifyReply,
  deps: AddOnsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ApproveAddOnPackageInput = {
    addOnId: request.params.addOnId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.approves.create.execute(input);
  return reply.code(200).send(result);
}


