/**
 * ExecuteAttachIncidentPostMortem - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteAttachIncidentPostMortem Use Case
 *
 * DDD: Application use case for get PostMortem.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { AttachIncidentPostMortemInput, AttachIncidentPostMortemOutput } from "../dto/post-mortem.dto";
import type { ExecutionContextService, IdGeneratorService } from "@agentfence/services/_shared/index.js";
import type { PostMortemRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteAttachIncidentPostMortem {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly postMortem: PostMortemRepository
  ) {}

  async execute(input: AttachIncidentPostMortemInput): Promise<AttachIncidentPostMortemOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.incId();

    // All field names extracted from OpenAPI spec: notifyMarketplaceSuspension, postMortem
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).incidentId) {
      throw new ValidationError("incidentId is required");
    }
    const incidentId = (input as any).incidentId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.postMortem.attachIncidentPostMortem({ incidentId: incidentId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${incidentId}`);
    }

    return entity as AttachIncidentPostMortemOutput;
  }
}
