/**
 * ArmRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kill-switch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ArmRepository Port
 *
 * DDD: Application port for armrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ArmKillSwitchInput, ArmKillSwitchOutput } from "../dto/arm.dto";
export interface ArmRepository {
  armKillSwitch(input: ArmKillSwitchInput): Promise<ArmKillSwitchOutput>;
}

export type { ArmKillSwitchInput, ArmKillSwitchOutput } from "../dto/arm.dto";
