/**
 * OrderRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kill-switch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OrderRepository Port
 *
 * DDD: Application port for orderrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetKillSwitchOrderInput, GetKillSwitchOrderOutput, InvokeKillSwitchInput, InvokeKillSwitchOutput, ListKillSwitchOrdersInput, ListKillSwitchOrdersOutput } from "../dto/order.dto";
export interface OrderRepository {
  listKillSwitchOrders(input: ListKillSwitchOrdersInput): Promise<ListKillSwitchOrdersOutput>;
  invokeKillSwitch(input: InvokeKillSwitchInput): Promise<InvokeKillSwitchOutput>;
  getKillSwitchOrder(input: GetKillSwitchOrderInput): Promise<GetKillSwitchOrderOutput>;
}

export type { GetKillSwitchOrderInput, GetKillSwitchOrderOutput, InvokeKillSwitchInput, InvokeKillSwitchOutput, ListKillSwitchOrdersInput, ListKillSwitchOrdersOutput } from "../dto/order.dto";
