/**
 * CreateHaltAck DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace-adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import { ulid } from "ulid";
import type { HaltAckRequest } from "@agentfence/core/marketplace-adapters";
import { marketplaceAdaptersSchemas } from "@agentfence/core/marketplace-adapters";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "mkt";

export function createCreateHaltAckRequest(overrides: Partial<HaltAckRequest> = {}) {
  const raw = {
    halted: overrides.halted ?? faker.datatype.boolean(),
    orderId: overrides.orderId ?? `ksw_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return marketplaceAdaptersSchemas.HaltAckRequest.parse(raw);
}
