/**
 * HaltAck DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace-adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HaltAck DTOs
 *
 * DDD: Application DTOs for HaltAck use cases.
 */

import type { AcknowledgeHaltParams, HaltAckRequest } from "@agentfence/core/marketplace-adapters/types";

export type AcknowledgeHaltInput = AcknowledgeHaltParams & HaltAckRequest;

export type AcknowledgeHaltOutput = {};
