/**
 * System Routes - Health check and routes listing
 *
 * AUTO-GENERATED by codegen (api_server_system_routes). Do not edit by hand.
 * Domains and routeExamples are derived from discovered api-server domains and
 * each domain's OpenAPI bundled spec.
 */

import type { FastifyInstance } from "fastify";
import {
  getCoreTableName,
  getBaseTableName,
  getAnalyticsTableName,
} from "@agentfence/adapters";
import { getRegisteredRoutes } from "./route-registry.js";

/**
 * Register system routes (health check, routes listing)
 */
export function registerSystemRoutes(fastify: FastifyInstance): void {
  // Health check (public - no auth required)
  fastify.get("/health", { config: { scope: "public" } }, async () => {
    try {
      const coreTable = getCoreTableName();
      const baseTable = getBaseTableName();
      const analyticsTable = getAnalyticsTableName();
      return {
        status: "ok",
        database: "dynamodb",
        tables: {
          core: coreTable,
          base: baseTable,
          analytics: analyticsTable,
        },
      };
    } catch (error: unknown) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      fastify.log.warn({ error: errorMessage }, "Health check failed");
      return { status: "error", database: "disconnected", error: errorMessage };
    }
  });

  // Routes listing endpoint (public)
  fastify.get("/routes", { config: { scope: "public" } }, async () => {
    const domains = [
      "add-ons", "agents", "audits", "delegations", "identity", "incidents", "kill-switch", "marketplace-adapters", "policies", "reporting"
    ];

    const routeExamples: Record<
      string,
      Array<{ method: string; path: string; description?: string }>
    > = {
      "add-ons": [{ method: "GET", path: "/v1/add-ons" }, { method: "POST", path: "/v1/add-ons" }, { method: "GET", path: "/v1/add-ons/:addOnId" }, { method: "POST", path: "/v1/add-ons/:addOnId/approve" }, { method: "POST", path: "/v1/add-ons/:addOnId/revoke" }, { method: "POST", path: "/v1/add-ons/:addOnId/unload" }],
      agents: [{ method: "GET", path: "/v1/agents" }, { method: "POST", path: "/v1/agents" }, { method: "GET", path: "/v1/agents/shadow-conflicts" }, { method: "GET", path: "/v1/agents/:agentId" }, { method: "PATCH", path: "/v1/agents/:agentId" }, { method: "POST", path: "/v1/agents/:agentId/rotate-credentials" }, { method: "POST", path: "/v1/agents/:agentId/marketplace-ids" }, { method: "POST", path: "/v1/agents/:agentId/suspend" }],
      audits: [{ method: "GET", path: "/v1/audits/events" }, { method: "POST", path: "/v1/audits/events" }, { method: "GET", path: "/v1/audits/events/:eventId" }, { method: "POST", path: "/v1/audits/verify-chain" }],
      delegations: [{ method: "GET", path: "/v1/delegations" }, { method: "POST", path: "/v1/delegations" }, { method: "GET", path: "/v1/delegations/graph" }, { method: "GET", path: "/v1/delegations/:delegationId" }, { method: "GET", path: "/v1/delegations/:delegationId/inheritance" }],
      identity: [{ method: "GET", path: "/v0/tenants/me/api-keys" }, { method: "POST", path: "/v0/tenants/me/api-keys" }, { method: "GET", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "DELETE", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "GET", path: "/v0/tenants/me/users" }, { method: "POST", path: "/v0/tenants/me/users" }, { method: "GET", path: "/v0/tenants/me/users/:userId" }, { method: "PATCH", path: "/v0/tenants/me/users/:userId" }, { method: "POST", path: "/v0/tenants/me/users/:userId/disable" }, { method: "POST", path: "/v0/tenants/me/users/:userId/enable" }, { method: "POST", path: "/v0/auth/login" }, { method: "GET", path: "/v0/auth/me" }, { method: "PATCH", path: "/v0/auth/me" }, { method: "POST", path: "/v0/auth/refresh" }, { method: "POST", path: "/v0/auth/logout" }],
      incidents: [{ method: "GET", path: "/v1/incidents" }, { method: "POST", path: "/v1/incidents" }, { method: "GET", path: "/v1/incidents/:incidentId" }, { method: "POST", path: "/v1/incidents/:incidentId/close" }, { method: "POST", path: "/v1/incidents/:incidentId/post-mortem" }],
      "kill-switch": [{ method: "GET", path: "/v1/kill-switch/orders" }, { method: "POST", path: "/v1/kill-switch/orders" }, { method: "GET", path: "/v1/kill-switch/orders/:orderId" }, { method: "POST", path: "/v1/kill-switch/orders/:orderId/arm" }, { method: "GET", path: "/v1/kill-switch/orders/:orderId/blast-radius" }, { method: "POST", path: "/v1/kill-switch/orders/:orderId/acks" }],
      "marketplace-adapters": [{ method: "GET", path: "/v1/marketplace-adapters" }, { method: "POST", path: "/v1/marketplace-adapters" }, { method: "GET", path: "/v1/marketplace-adapters/:adapterId" }, { method: "POST", path: "/v1/marketplace-adapters/:adapterId/halt-ack" }, { method: "GET", path: "/v1/partner-attestations/:agentId" }],
      policies: [{ method: "GET", path: "/v1/policies" }, { method: "POST", path: "/v1/policies" }, { method: "POST", path: "/v1/policies/evaluate" }, { method: "POST", path: "/v1/policies/simulate" }, { method: "POST", path: "/v1/policies/exceptions" }, { method: "GET", path: "/v1/policies/:policyId" }, { method: "PATCH", path: "/v1/policies/:policyId" }, { method: "POST", path: "/v1/policies/:policyId/publish" }],
      reporting: [{ method: "GET", path: "/v1/reports/compliance" }, { method: "GET", path: "/v1/reports" }, { method: "POST", path: "/v1/reports" }, { method: "GET", path: "/v1/reports/:reportId" }],
    };

    return {
      baseUrl: "http://localhost:4000",
      routePattern: "/orgs/:orgId/{domain}/{resource}",
      authentication:
        "All routes (except /health and /routes) require JWT token in Authorization header",
      domains: domains.sort(),
      routeExamples,
      systemRoutes: [
        { method: "GET", path: "/health", description: "Health check endpoint" },
        { method: "GET", path: "/routes", description: "List available routes" },
      ],
      note: "Replace :orgId with actual organization ID. All domain routes require authentication.",
    };
  });

  // Full route list for API tester page (public)
  fastify.get("/routes/full", { config: { scope: "public" } }, async () => {
    const routes = getRegisteredRoutes();
    const byDomain: Record<
      string,
      Array<{ method: string; path: string }>
    > = {};
    const system: Array<{ method: string; path: string }> = [];
    for (const r of routes) {
      const m = r.path.match(/^\/orgs\/:orgId\/([^/]+)/);
      if (m) {
        const domain = m[1];
        if (!byDomain[domain]) byDomain[domain] = [];
        byDomain[domain].push(r);
      } else {
        system.push(r);
      }
    }
    return {
      baseUrl: "http://localhost:4000",
      total: routes.length,
      system,
      byDomain: Object.keys(byDomain)
        .sort()
        .reduce(
          (acc, k) => ({ ...acc, [k]: byDomain[k] }),
          {} as Record<string, Array<{ method: string; path: string }>>,
        ),
    };
  });
}
