/**
 * PostMortem DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PostMortem DTOs
 *
 * DDD: Application DTOs for PostMortem use cases.
 */

import type { AttachIncidentPostMortemParams, IncidentPostMortemRequest } from "@agentfence/core/incidents/types";

export type AttachIncidentPostMortemInput = AttachIncidentPostMortemParams & IncidentPostMortemRequest;

export type AttachIncidentPostMortemOutput = {};
