/**
 * CreateRevoke DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: add-ons
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { AddOnRevokeRequest } from "@agentfence/core/add-ons";
import { addOnsSchemas } from "@agentfence/core/add-ons";

export function createCreateRevokeRequest(overrides: Partial<AddOnRevokeRequest> = {}) {
  const raw = {
    rationale: overrides.rationale ?? faker.lorem.word(),
    ...overrides,
  };

  return addOnsSchemas.AddOnRevokeRequest.parse(raw);
}
