/**
 * Policy DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Policy DTOs
 *
 * DDD: Application DTOs for Policy use cases.
 */

import type { AutonomyPolicyCreateRequest, AutonomyPolicyUpdateRequest, GetAutonomyPolicyParams, ListAutonomyPoliciesParams, UpdateAutonomyPolicyParams } from "@agentfence/core/policies/types";

export type ListAutonomyPoliciesInput = ListAutonomyPoliciesParams;

export type CreateAutonomyPolicyInput = AutonomyPolicyCreateRequest;

export type GetAutonomyPolicyInput = GetAutonomyPolicyParams;

export type UpdateAutonomyPolicyInput = UpdateAutonomyPolicyParams & AutonomyPolicyUpdateRequest;

export type ListAutonomyPoliciesOutput = {};

export type CreateAutonomyPolicyOutput = {};

export type GetAutonomyPolicyOutput = {};

export type UpdateAutonomyPolicyOutput = {};
