/**
 * CreateDelegation DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: delegations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { ulid } from "ulid";
import type { DelegationEdgeCreateRequest } from "@agentfence/core/delegations";
import { delegationsSchemas } from "@agentfence/core/delegations";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "dlg";

export function createCreateDelegationRequest(overrides: Partial<DelegationEdgeCreateRequest> = {}) {
  const raw = {
    childAgentId: overrides.childAgentId ?? `agt_${ulid().toLowerCase()}`,
    parentAgentId: overrides.parentAgentId ?? `agt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return delegationsSchemas.DelegationEdgeCreateRequest.parse(raw);
}
