/**
 * ListDelegation DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: delegations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListDelegationEdgesParams } from "@agentfence/core/delegations";

export function createListDelegationRequest(overrides: Partial<ListDelegationEdgesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
