/**
 * Agents DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Agents Domain Module - Composition root
 *
 * DDD: Composition root for agents domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AgentRepositoryAdapter,
  MarketplaceIdRepositoryAdapter,
  ShadowConflictRepositoryAdapter,
  SuspendRepositoryAdapter,
} from "@agentfence/adapters/agents";
import { getIdGeneratorService } from "@agentfence/adapters";
import type { AdapterDynamoDBClient } from "@agentfence/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetAgent,
  ExecuteListAgents,
  ExecuteListShadowAgentConflicts,
  ExecuteMapAgentMarketplaceIds,
  ExecuteRegisterAgent,
  ExecuteRotateAgentCredentials,
  ExecuteSuspendAgent,
  ExecuteUpdateAgent,
} from "@agentfence/services/agents/usecases";
// Ports (interfaces)
import type {
  AgentRepository,
  MarketplaceIdRepository,
  ShadowConflictRepository,
  SuspendRepository,
} from "@agentfence/services/agents/ports";

export interface AgentsDomainModule {
  repos: {
    agents: AgentRepository;
    marketplaceIds: MarketplaceIdRepository;
    shadowConflicts: ShadowConflictRepository;
    suspends: SuspendRepository;
  };
  useCases: {
    agents: {
      create: ExecuteRegisterAgent;
      get: ExecuteGetAgent;
      list: ExecuteListAgents;
      update: ExecuteUpdateAgent;
    };
    marketplaceIds: {
      get: ExecuteMapAgentMarketplaceIds;
    };
    shadowConflicts: {
      list: ExecuteListShadowAgentConflicts;
    };
    suspends: {
      get: ExecuteSuspendAgent;
    };
  };
}

export function buildAgentsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AgentsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      agents?: AgentRepository;
      marketplaceIds?: MarketplaceIdRepository;
      shadowConflicts?: ShadowConflictRepository;
      suspends?: SuspendRepository;
    } = {};

    obj.agents = new AgentRepositoryAdapter(dynamoClient);
    obj.marketplaceIds = new MarketplaceIdRepositoryAdapter(dynamoClient);
    obj.shadowConflicts = new ShadowConflictRepositoryAdapter(dynamoClient);
    obj.suspends = new SuspendRepositoryAdapter(dynamoClient);
    return {
      agents: obj.agents!,
      marketplaceIds: obj.marketplaceIds!,
      shadowConflicts: obj.shadowConflicts!,
      suspends: obj.suspends!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    agents: {
      create: new ExecuteRegisterAgent(executionContext, idGenerator, repos.agents),
      get: new ExecuteGetAgent(executionContext, idGenerator, repos.agents),
      list: new ExecuteListAgents(executionContext, idGenerator, repos.agents),
      update: new ExecuteUpdateAgent(executionContext, idGenerator, repos.agents),
    },
    marketplaceIds: {
      get: new ExecuteMapAgentMarketplaceIds(executionContext, idGenerator, repos.marketplaceIds),
    },
    shadowConflicts: {
      list: new ExecuteListShadowAgentConflicts(executionContext, idGenerator, repos.shadowConflicts),
    },
    suspends: {
      get: new ExecuteSuspendAgent(executionContext, idGenerator, repos.suspends),
    },
  };
  return { repos, useCases: useCases as AgentsDomainModule["useCases"] };
}
