/**
 * GraphRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: delegations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GraphRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements GraphRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  GraphRepository,
} from "@agentfence/services/delegations";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { GraphRepositoryDdb } from "./graph-repository.ddb.js";

/**
 * GraphRepositoryAdapter
 *
 * Implements GraphRepository port for infrastructure layer.
 */
export class GraphRepositoryAdapter implements GraphRepository {
  private readonly ddb: GraphRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new GraphRepositoryDdb(this.dynamoClient);
  }

  async getDelegationGraph(input: Parameters<GraphRepository['getDelegationGraph']>[0]): Promise<Awaited<ReturnType<GraphRepository['getDelegationGraph']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDelegationGraph(input);
  }
}
