/**
 * ExecuteAcknowledgeHalt - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace-adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteAcknowledgeHalt Use Case
 *
 * DDD: Application use case for get HaltAck.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { AcknowledgeHaltInput, AcknowledgeHaltOutput } from "../dto/halt-ack.dto";
import type { ExecutionContextService, IdGeneratorService } from "@agentfence/services/_shared/index.js";
import type { HaltAckRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteAcknowledgeHalt {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly haltAck: HaltAckRepository
  ) {}

  async execute(input: AcknowledgeHaltInput): Promise<AcknowledgeHaltOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.mktId();

    // All field names extracted from OpenAPI spec: detail, halted, orderId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).adapterId) {
      throw new ValidationError("adapterId is required");
    }
    const adapterId = (input as any).adapterId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.haltAck.acknowledgeHalt({ adapterId: adapterId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${adapterId}`);
    }

    return entity as AcknowledgeHaltOutput;
  }
}
