/**
 * CreateAck DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kill-switch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import { ulid } from "ulid";
import type { KillSwitchAckRequest } from "@agentfence/core/kill-switch";
import { killSwitchSchemas } from "@agentfence/core/kill-switch";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ksw";

export function createCreateAckRequest(overrides: Partial<KillSwitchAckRequest> = {}) {
  const raw = {
    adapterId: overrides.adapterId ?? `mkt_${ulid().toLowerCase()}`,
    halted: overrides.halted ?? faker.datatype.boolean(),
    ...overrides,
  };

  return killSwitchSchemas.KillSwitchAckRequest.parse(raw);
}
