/**
 * ExecuteListAddOnPackages - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: add-ons
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListAddOnPackages Use Case
 *
 * DDD: Application use case for list AddOn.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListAddOnPackagesInput, ListAddOnPackagesOutput } from "../dto/add-on.dto";
import type { ExecutionContextService, IdGeneratorService } from "@agentfence/services/_shared/index.js";
import type { AddOnRepository } from "../ports";

export class ExecuteListAddOnPackages {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly addOn: AddOnRepository
  ) {}

  async execute(input: ListAddOnPackagesInput): Promise<ListAddOnPackagesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.adoId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.addOn.listAddOnPackages({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListAddOnPackagesOutput;
  }
}
