/**
 * ExecuteGetAddOnPackage - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: add-ons
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetAddOnPackage Use Case
 *
 * DDD: Application use case for get AddOn.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetAddOnPackageInput, GetAddOnPackageOutput } from "../dto/add-on.dto";
import type { ExecutionContextService, IdGeneratorService } from "@agentfence/services/_shared/index.js";
import type { AddOnRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetAddOnPackage {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly addOn: AddOnRepository
  ) {}

  async execute(input: GetAddOnPackageInput): Promise<GetAddOnPackageOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.adoId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).addOnId) {
      throw new ValidationError("addOnId is required");
    }
    const addonId = (input as any).addOnId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.addOn.getAddOnPackage({ addOnId: addonId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${addonId}`);
    }

    return entity as GetAddOnPackageOutput;
  }
}
