/**
 * CreateSuspend DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { AgentSuspendRequest } from "@agentfence/core/agents";
import { agentsSchemas } from "@agentfence/core/agents";

export function createCreateSuspendRequest(overrides: Partial<AgentSuspendRequest> = {}) {
  const raw = {
    rationale: overrides.rationale ?? faker.lorem.word(),
    ...overrides,
  };

  return agentsSchemas.AgentSuspendRequest.parse(raw);
}
