/**
 * Handlers for Arm
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kill-switch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { KillSwitchDomainModule } from "../dependencies/kill-switch-ddd.dependencies.js";
import type { KillSwitchArmRequest } from "@agentfence/core/kill-switch/types";
import type { ArmKillSwitchInput } from "@agentfence/services/kill-switch";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/kill-switch/orders/{orderId}/arm
 * Operation: armKillSwitch
 */
export async function armKillSwitch(
  request: FastifyRequest<{ Params: { orderId: string }; Querystring: Record<string, string | string[] | undefined>; Body: KillSwitchArmRequest }>,
  reply: FastifyReply,
  deps: KillSwitchDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ArmKillSwitchInput = {
    orderId: request.params.orderId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.arms.get.execute(input);
  return reply.code(200).send(result);
}


