/**
 * Handlers for BlastRadiu
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kill-switch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { KillSwitchDomainModule } from "../dependencies/kill-switch-ddd.dependencies.js";
import type { GetKillSwitchBlastRadiusInput } from "@agentfence/services/kill-switch";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/kill-switch/orders/{orderId}/blast-radius
 * Operation: getKillSwitchBlastRadius
 */
export async function getKillSwitchBlastRadius(
  request: FastifyRequest<{ Params: { orderId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: KillSwitchDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetKillSwitchBlastRadiusInput = {
    orderId: request.params.orderId,
  };
  const result = await deps.useCases.blastRadius.get.execute(input);
  return reply.code(200).send(result);
}


