/**
 * ExecuteListAgents - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListAgents Use Case
 *
 * DDD: Application use case for list Agent.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListAgentsInput, ListAgentsOutput } from "../dto/agent.dto";
import type { ExecutionContextService, IdGeneratorService } from "@agentfence/services/_shared/index.js";
import type { AgentRepository } from "../ports";

export class ExecuteListAgents {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly agent: AgentRepository
  ) {}

  async execute(input: ListAgentsInput): Promise<ListAgentsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.agtId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.agent.listAgents({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListAgentsOutput;
  }
}
