/**
 * ExecuteMapAgentMarketplaceIds - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteMapAgentMarketplaceIds Use Case
 *
 * DDD: Application use case for get MarketplaceId.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { MapAgentMarketplaceIdsInput, MapAgentMarketplaceIdsOutput } from "../dto/marketplace-id.dto";
import type { ExecutionContextService, IdGeneratorService } from "@agentfence/services/_shared/index.js";
import type { MarketplaceIdRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteMapAgentMarketplaceIds {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly marketplaceId: MarketplaceIdRepository
  ) {}

  async execute(input: MapAgentMarketplaceIdsInput): Promise<MapAgentMarketplaceIdsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.agtId();

    // All field names extracted from OpenAPI spec: externalId, marketplace
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).agentId) {
      throw new ValidationError("agentId is required");
    }
    const agentId = (input as any).agentId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.marketplaceId.mapAgentMarketplaceIds({ agentId: agentId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${agentId}`);
    }

    return entity as MapAgentMarketplaceIdsOutput;
  }
}
