/**
 * VerifyChain DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VerifyChain DTOs
 *
 * DDD: Application DTOs for VerifyChain use cases.
 */

import type { AuditChainVerifyRequest } from "@agentfence/core/audits/types";

export type VerifyAuditChainInput = AuditChainVerifyRequest;

export type VerifyAuditChainOutput = {};
