/**
 * CreatePolicy DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { ulid } from "ulid";
import type { AutonomyPolicyCreateRequest } from "@agentfence/core/policies";
import { policiesSchemas } from "@agentfence/core/policies";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "pol";

export function createCreatePolicyRequest(overrides: Partial<AutonomyPolicyCreateRequest> = {}) {
  const raw = {
    agentId: overrides.agentId ?? `agt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return policiesSchemas.AutonomyPolicyCreateRequest.parse(raw);
}
