/**
 * VerifyChainRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VerifyChainRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements VerifyChainRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  VerifyChainRepository,
} from "@agentfence/services/audits";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { VerifyChainRepositoryDdb } from "./verify-chain-repository.ddb.js";

/**
 * VerifyChainRepositoryAdapter
 *
 * Implements VerifyChainRepository port for infrastructure layer.
 */
export class VerifyChainRepositoryAdapter implements VerifyChainRepository {
  private readonly ddb: VerifyChainRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new VerifyChainRepositoryDdb(this.dynamoClient);
  }

  async verifyAuditChain(input: Parameters<VerifyChainRepository['verifyAuditChain']>[0]): Promise<Awaited<ReturnType<VerifyChainRepository['verifyAuditChain']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.verifyAuditChain(input);
  }
}
