/**
 * CreateIncident DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { IncidentCreateRequest } from "@agentfence/core/incidents";
import { incidentsSchemas } from "@agentfence/core/incidents";

export function createCreateIncidentRequest(overrides: Partial<IncidentCreateRequest> = {}) {
  const raw = {
    title: overrides.title ?? faker.lorem.sentence(),
    ...overrides,
  };

  return incidentsSchemas.IncidentCreateRequest.parse(raw);
}
