/**
 * PolicyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PolicyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PolicyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PolicyRepository,
} from "@agentfence/services/policies";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PolicyRepositoryDdb } from "./policy-repository.ddb.js";

/**
 * PolicyRepositoryAdapter
 *
 * Implements PolicyRepository port for infrastructure layer.
 */
export class PolicyRepositoryAdapter implements PolicyRepository {
  private readonly ddb: PolicyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PolicyRepositoryDdb(this.dynamoClient);
  }

  async listAutonomyPolicies(input: Parameters<PolicyRepository['listAutonomyPolicies']>[0]): Promise<Awaited<ReturnType<PolicyRepository['listAutonomyPolicies']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAutonomyPolicies(input);
  }

  async createAutonomyPolicy(input: Parameters<PolicyRepository['createAutonomyPolicy']>[0]): Promise<Awaited<ReturnType<PolicyRepository['createAutonomyPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createAutonomyPolicy(input);
  }

  async getAutonomyPolicy(input: Parameters<PolicyRepository['getAutonomyPolicy']>[0]): Promise<Awaited<ReturnType<PolicyRepository['getAutonomyPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getAutonomyPolicy(input);
  }

  async updateAutonomyPolicy(input: Parameters<PolicyRepository['updateAutonomyPolicy']>[0]): Promise<Awaited<ReturnType<PolicyRepository['updateAutonomyPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateAutonomyPolicy(input);
  }
}
