/**
 * SimulateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SimulateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SimulateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SimulateRepository,
} from "@agentfence/services/policies";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SimulateRepositoryDdb } from "./simulate-repository.ddb.js";

/**
 * SimulateRepositoryAdapter
 *
 * Implements SimulateRepository port for infrastructure layer.
 */
export class SimulateRepositoryAdapter implements SimulateRepository {
  private readonly ddb: SimulateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SimulateRepositoryDdb(this.dynamoClient);
  }

  async simulateAgentAction(input: Parameters<SimulateRepository['simulateAgentAction']>[0]): Promise<Awaited<ReturnType<SimulateRepository['simulateAgentAction']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.simulateAgentAction(input);
  }
}
