/**
 * KillSwitch DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kill-switch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * KillSwitch Domain Module - Composition root
 *
 * DDD: Composition root for kill-switch domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AckRepositoryAdapter,
  ArmRepositoryAdapter,
  BlastRadiuRepositoryAdapter,
  OrderRepositoryAdapter,
} from "@agentfence/adapters/kill-switch";
import { getIdGeneratorService } from "@agentfence/adapters";
import type { AdapterDynamoDBClient } from "@agentfence/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteArmKillSwitch,
  ExecuteGetKillSwitchOrder,
  ExecuteInvokeKillSwitch,
  ExecuteListKillSwitchOrders,
  ExecuteRecordKillSwitchAck,
} from "@agentfence/services/kill-switch/usecases";
// Ports (interfaces)
import type {
  AckRepository,
  ArmRepository,
  BlastRadiuRepository,
  OrderRepository,
} from "@agentfence/services/kill-switch/ports";

export interface KillSwitchDomainModule {
  repos: {
    acks: AckRepository;
    arms: ArmRepository;
    blastRadius: BlastRadiuRepository;
    orders: OrderRepository;
  };
  useCases: {
    acks: {
      get: ExecuteRecordKillSwitchAck;
    };
    arms: {
      get: ExecuteArmKillSwitch;
    };
    orders: {
      create: ExecuteInvokeKillSwitch;
      get: ExecuteGetKillSwitchOrder;
      list: ExecuteListKillSwitchOrders;
    };
  };
}

export function buildKillSwitchDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): KillSwitchDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      acks?: AckRepository;
      arms?: ArmRepository;
      blastRadius?: BlastRadiuRepository;
      orders?: OrderRepository;
    } = {};

    obj.acks = new AckRepositoryAdapter(dynamoClient);
    obj.arms = new ArmRepositoryAdapter(dynamoClient);
    obj.blastRadius = new BlastRadiuRepositoryAdapter(dynamoClient);
    obj.orders = new OrderRepositoryAdapter(dynamoClient);
    return {
      acks: obj.acks!,
      arms: obj.arms!,
      blastRadius: obj.blastRadius!,
      orders: obj.orders!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    acks: {
      get: new ExecuteRecordKillSwitchAck(executionContext, idGenerator, repos.acks),
    },
    arms: {
      get: new ExecuteArmKillSwitch(executionContext, idGenerator, repos.arms),
    },
    orders: {
      create: new ExecuteInvokeKillSwitch(executionContext, idGenerator, repos.orders),
      get: new ExecuteGetKillSwitchOrder(executionContext, idGenerator, repos.orders),
      list: new ExecuteListKillSwitchOrders(executionContext, idGenerator, repos.orders),
    },
  };
  return { repos, useCases: useCases as KillSwitchDomainModule["useCases"] };
}
