/**
 * CreateEvent DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import { ulid } from "ulid";
import type { AuditEventCreateRequest } from "@agentfence/core/audits";
import { auditsSchemas } from "@agentfence/core/audits";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "aud";

export function createCreateEventRequest(overrides: Partial<AuditEventCreateRequest> = {}) {
  const raw = {
    actionType: overrides.actionType ?? faker.lorem.word(),
    agentId: overrides.agentId ?? `agt_${ulid().toLowerCase()}`,
    outcome: overrides.outcome ?? "allowed",
    ...overrides,
  };

  return auditsSchemas.AuditEventCreateRequest.parse(raw);
}
