/**
 * CreatePostMortem DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { IncidentPostMortemRequest } from "@agentfence/core/incidents";
import { incidentsSchemas } from "@agentfence/core/incidents";

export function createCreatePostMortemRequest(overrides: Partial<IncidentPostMortemRequest> = {}) {
  const raw = {
    postMortem: overrides.postMortem ?? faker.lorem.word(),
    ...overrides,
  };

  return incidentsSchemas.IncidentPostMortemRequest.parse(raw);
}
