/**
 * Audits DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Audits Domain Module - Composition root
 *
 * DDD: Composition root for audits domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  EventRepositoryAdapter,
  VerifyChainRepositoryAdapter,
} from "@agentfence/adapters/audits";
import { getIdGeneratorService } from "@agentfence/adapters";
import type { AdapterDynamoDBClient } from "@agentfence/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAppendAuditEvent,
  ExecuteGetAuditEvent,
  ExecuteListAuditEvents,
} from "@agentfence/services/audits/usecases";
// Ports (interfaces)
import type {
  EventRepository,
  VerifyChainRepository,
} from "@agentfence/services/audits/ports";

export interface AuditsDomainModule {
  repos: {
    events: EventRepository;
    verifyChains: VerifyChainRepository;
  };
  useCases: {
    events: {
      get: ExecuteGetAuditEvent;
      list: ExecuteListAuditEvents;
    };
  };
}

export function buildAuditsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AuditsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      events?: EventRepository;
      verifyChains?: VerifyChainRepository;
    } = {};

    obj.events = new EventRepositoryAdapter(dynamoClient);
    obj.verifyChains = new VerifyChainRepositoryAdapter(dynamoClient);
    return {
      events: obj.events!,
      verifyChains: obj.verifyChains!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    events: {
      get: new ExecuteGetAuditEvent(executionContext, idGenerator, repos.events),
      list: new ExecuteListAuditEvents(executionContext, idGenerator, repos.events),
    },
  };
  return { repos, useCases: useCases as AuditsDomainModule["useCases"] };
}
