/**
 * ShadowConflict Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/agents.openapi.types.js";
import { schemas } from "../schemas/agents.schemas.js";

/**
 * Entity: ShadowConflictEntity
 * Description: Represents the ShadowConflict domain model.
 * Source: schemas.ShadowConflict
 * Type: Domain Entity (API)
 */
export const ShadowConflictEntitySchema = schemas.ShadowConflict;
export type ShadowConflictEntity = components["schemas"]["ShadowConflict"];
