/**
 * Handlers for PartnerAttestation
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace-adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { MarketplaceAdaptersDomainModule } from "../dependencies/marketplace-adapters-ddd.dependencies.js";
import type { VerifyPartnerAttestationInput } from "@agentfence/services/marketplace-adapters";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/partner-attestations/{agentId}
 * Operation: verifyPartnerAttestation
 */
export async function verifyPartnerAttestation(
  request: FastifyRequest<{ Params: { agentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: MarketplaceAdaptersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: VerifyPartnerAttestationInput = {
    agentId: request.params.agentId,
  };
  const result = await deps.useCases.partnerAttestations.get.execute(input);
  return reply.code(200).send(result);
}


