/**
 * IncidentRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * IncidentRepository Port
 *
 * DDD: Application port for incidentrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateIncidentInput, CreateIncidentOutput, GetIncidentInput, GetIncidentOutput, ListIncidentsInput, ListIncidentsOutput } from "../dto/incident.dto";
export interface IncidentRepository {
  listIncidents(input: ListIncidentsInput): Promise<ListIncidentsOutput>;
  createIncident(input: CreateIncidentInput): Promise<CreateIncidentOutput>;
  getIncident(input: GetIncidentInput): Promise<GetIncidentOutput>;
}

export type { CreateIncidentInput, CreateIncidentOutput, GetIncidentInput, GetIncidentOutput, ListIncidentsInput, ListIncidentsOutput } from "../dto/incident.dto";
