/**
 * ShadowConflict DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ShadowConflict DTOs
 *
 * DDD: Application DTOs for ShadowConflict use cases.
 */

export type ListShadowAgentConflictsInput = {};

export type ListShadowAgentConflictsOutput = {};
