/**
 * Handlers for Agent
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AgentsDomainModule } from "../dependencies/agents-ddd.dependencies.js";
import type { AgentRegisterRequest, AgentUpdateRequest } from "@agentfence/core/agents/types";
import type { GetAgentInput, ListAgentsInput, RegisterAgentInput, UpdateAgentInput } from "@agentfence/services/agents";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/agents
 * Operation: listAgents
 */
export async function listAgents(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AgentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListAgentsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.agents.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/agents
 * Operation: registerAgent
 */
export async function registerAgent(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: AgentRegisterRequest }>,
  reply: FastifyReply,
  deps: AgentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RegisterAgentInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.agents.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/agents/{agentId}
 * Operation: getAgent
 */
export async function getAgent(
  request: FastifyRequest<{ Params: { agentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AgentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetAgentInput = {
    agentId: request.params.agentId,
  };
  const result = await deps.useCases.agents.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/agents/{agentId}
 * Operation: updateAgent
 */
export async function updateAgent(
  request: FastifyRequest<{ Params: { agentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: AgentUpdateRequest }>,
  reply: FastifyReply,
  deps: AgentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateAgentInput = {
    agentId: request.params.agentId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.agents.update.execute(input);
  return reply.code(200).send(result);
}


