/**
 * Handlers for RotateCredential
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AgentsDomainModule } from "../dependencies/agents-ddd.dependencies.js";
import type { RotateAgentCredentialsInput } from "@agentfence/services/agents";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/agents/{agentId}/rotate-credentials
 * Operation: rotateAgentCredentials
 */
export async function rotateAgentCredentials(
  request: FastifyRequest<{ Params: { agentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AgentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RotateAgentCredentialsInput = {
    agentId: request.params.agentId,
  };
  const result = await deps.useCases.rotateCredentials.get.execute(input);
  return reply.code(200).send(result);
}


