/**
 * Handlers for ShadowConflict
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AgentsDomainModule } from "../dependencies/agents-ddd.dependencies.js";
import type { ListShadowAgentConflictsInput } from "@agentfence/services/agents";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/agents/shadow-conflicts
 * Operation: listShadowAgentConflicts
 */
export async function listShadowAgentConflicts(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: AgentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListShadowAgentConflictsInput = {};
  const result = await deps.useCases.shadowConflicts.list.execute(input);
  return reply.code(200).send(result);
}


