/**
 * Handlers for Suspend
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AgentsDomainModule } from "../dependencies/agents-ddd.dependencies.js";
import type { AgentSuspendRequest } from "@agentfence/core/agents/types";
import type { SuspendAgentInput } from "@agentfence/services/agents";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/agents/{agentId}/suspend
 * Operation: suspendAgent
 */
export async function suspendAgent(
  request: FastifyRequest<{ Params: { agentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: AgentSuspendRequest }>,
  reply: FastifyReply,
  deps: AgentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SuspendAgentInput = {
    agentId: request.params.agentId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.suspends.get.execute(input);
  return reply.code(200).send(result);
}


