/**
 * ExecuteListDelegationEdges - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: delegations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDelegationEdges Use Case
 *
 * DDD: Application use case for list Delegation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDelegationEdgesInput, ListDelegationEdgesOutput } from "../dto/delegation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@agentfence/services/_shared/index.js";
import type { DelegationRepository } from "../ports";

export class ExecuteListDelegationEdges {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly delegation: DelegationRepository
  ) {}

  async execute(input: ListDelegationEdgesInput): Promise<ListDelegationEdgesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dlgId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.delegation.listDelegationEdges({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDelegationEdgesOutput;
  }
}
