/**
 * ExecuteGetDelegationEdge - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: delegations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetDelegationEdge Use Case
 *
 * DDD: Application use case for get Delegation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetDelegationEdgeInput, GetDelegationEdgeOutput } from "../dto/delegation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@agentfence/services/_shared/index.js";
import type { DelegationRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetDelegationEdge {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly delegation: DelegationRepository
  ) {}

  async execute(input: GetDelegationEdgeInput): Promise<GetDelegationEdgeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dlgId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).delegationId) {
      throw new ValidationError("delegationId is required");
    }
    const delegationId = (input as any).delegationId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.delegation.getDelegationEdge({ delegationId: delegationId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${delegationId}`);
    }

    return entity as GetDelegationEdgeOutput;
  }
}
