/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kill-switch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * KillSwitch Domain Use Cases
 * 
 * List of all use case names for the kill-switch domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const KILLSWITCH_USE_CASES = [
  "executeArmKillSwitch",
  "executeGetKillSwitchBlastRadius",
  "executeGetKillSwitchOrder",
  "executeInvokeKillSwitch",
  "executeListKillSwitchOrders",
  "executeRecordKillSwitchAck"
] as const;
