/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildAddOnsDomainModule } from "./add-ons/dependencies/add-ons-ddd.dependencies.js";
export { buildAgentsDomainModule } from "./agents/dependencies/agents-ddd.dependencies.js";
export { buildAuditsDomainModule } from "./audits/dependencies/audits-ddd.dependencies.js";
export { buildDelegationsDomainModule } from "./delegations/dependencies/delegations-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildIncidentsDomainModule } from "./incidents/dependencies/incidents-ddd.dependencies.js";
export { buildKillSwitchDomainModule } from "./kill-switch/dependencies/kill-switch-ddd.dependencies.js";
export { buildMarketplaceAdaptersDomainModule } from "./marketplace-adapters/dependencies/marketplace-adapters-ddd.dependencies.js";
export { buildPoliciesDomainModule } from "./policies/dependencies/policies-ddd.dependencies.js";
export { buildReportingDomainModule } from "./reporting/dependencies/reporting-ddd.dependencies.js";

// Export all domain dependency types
export type { AddOnsDomainModule } from "./add-ons/dependencies/add-ons-ddd.dependencies.js";
export type { AgentsDomainModule } from "./agents/dependencies/agents-ddd.dependencies.js";
export type { AuditsDomainModule } from "./audits/dependencies/audits-ddd.dependencies.js";
export type { DelegationsDomainModule } from "./delegations/dependencies/delegations-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { IncidentsDomainModule } from "./incidents/dependencies/incidents-ddd.dependencies.js";
export type { KillSwitchDomainModule } from "./kill-switch/dependencies/kill-switch-ddd.dependencies.js";
export type { MarketplaceAdaptersDomainModule } from "./marketplace-adapters/dependencies/marketplace-adapters-ddd.dependencies.js";
export type { PoliciesDomainModule } from "./policies/dependencies/policies-ddd.dependencies.js";
export type { ReportingDomainModule } from "./reporting/dependencies/reporting-ddd.dependencies.js";
