/**
 * Delegation DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: delegations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Delegation DTOs
 *
 * DDD: Application DTOs for Delegation use cases.
 */

import type { DelegationEdgeCreateRequest, GetDelegationEdgeParams, ListDelegationEdgesParams } from "@agentfence/core/delegations/types";

export type ListDelegationEdgesInput = ListDelegationEdgesParams;

export type CreateDelegationEdgeInput = DelegationEdgeCreateRequest;

export type GetDelegationEdgeInput = GetDelegationEdgeParams;

export type ListDelegationEdgesOutput = {};

export type CreateDelegationEdgeOutput = {};

export type GetDelegationEdgeOutput = {};
