/**
 * Inheritance DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: delegations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Inheritance DTOs
 *
 * DDD: Application DTOs for Inheritance use cases.
 */

import type { GetDelegationInheritanceParams } from "@agentfence/core/delegations/types";

export type GetDelegationInheritanceInput = GetDelegationInheritanceParams;

export type GetDelegationInheritanceOutput = {};
