/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: add-ons
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the add-ons domain.
 * Use these factories in tests to create test data.
 */

export { createCreateAddOnRequest } from "./add-on/dto/create-add-on.dto.factory.js";
export { createCreateApproveRequest } from "./approve/dto/create-approve.dto.factory.js";
export { createCreateRevokeRequest } from "./revoke/dto/create-revoke.dto.factory.js";
export { createCreateUnloadRequest } from "./unload/dto/create-unload.dto.factory.js";
