/**
 * ListOrder DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kill-switch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListKillSwitchOrdersParams } from "@agentfence/core/kill-switch";

export function createListOrderRequest(overrides: Partial<ListKillSwitchOrdersParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
