/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./get-agent.handler.test.js";
export * from "./list-agents.handler.test.js";
export * from "./register-agent.handler.test.js";
export * from "./update-agent.handler.test.js";
