/**
 * RegisterAgent handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { registerAgent } from "@agentfence/api-server/domains/agents/handlers";
import type { AgentsDDDDependencies } from "@agentfence/api-server/domains/agents";
import { createCreateAgentRequest } from "@agentfence/factories/agents";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@agentfence/tests/shared";
import { AGENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("RegisterAgent", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AgentsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AgentsDDDDependencies>(
      AGENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateAgentRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRegisterAgent, "execute").mockResolvedValue(useCaseResult);

    await registerAgent(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRegisterAgent.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
