/**
 * Routes for Event
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { appendAuditEvent, getAuditEvent, listAuditEvents } from "../handlers/event.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { AuditEventCreateRequest } from "@agentfence/core/audits/types";

// Fastify types are available globally
export async function eventRoutes(fastify: FastifyInstance) {
  // POST /v1/audits/events (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/audits/events",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: AuditEventCreateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAuditsDependenciesForRequest();
        await appendAuditEvent(request, reply, deps);
      });
    }
  );


  // GET /v1/audits/events (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/audits/events",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAuditsDependenciesForRequest();
        await listAuditEvents(request, reply, deps);
      });
    }
  );


  // GET /v1/audits/events/{eventId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/audits/events/:eventId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { eventId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAuditsDependenciesForRequest();
        await getAuditEvent(request, reply, deps);
      });
    }
  );


}
