/**
 * Routes for VerifyChain
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { verifyAuditChain } from "../handlers/verify-chain.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { AuditChainVerifyRequest } from "@agentfence/core/audits/types";

// Fastify types are available globally
export async function verifyChainRoutes(fastify: FastifyInstance) {
  // POST /v1/audits/verify-chain (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/audits/verify-chain",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: AuditChainVerifyRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAuditsDependenciesForRequest();
        await verifyAuditChain(request, reply, deps);
      });
    }
  );


}
