/**
 * ExecuteListKillSwitchOrders - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kill-switch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListKillSwitchOrders Use Case
 *
 * DDD: Application use case for list Order.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListKillSwitchOrdersInput, ListKillSwitchOrdersOutput } from "../dto/order.dto";
import type { ExecutionContextService, IdGeneratorService } from "@agentfence/services/_shared/index.js";
import type { OrderRepository } from "../ports";

export class ExecuteListKillSwitchOrders {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly order: OrderRepository
  ) {}

  async execute(input: ListKillSwitchOrdersInput): Promise<ListKillSwitchOrdersOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.kswId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.order.listKillSwitchOrders({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListKillSwitchOrdersOutput;
  }
}
