/**
 * CreateVerifyChain DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { ulid } from "ulid";
import type { AuditChainVerifyRequest } from "@agentfence/core/audits";
import { auditsSchemas } from "@agentfence/core/audits";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "aud";

export function createCreateVerifyChainRequest(overrides: Partial<AuditChainVerifyRequest> = {}) {
  const raw = {
    agentId: overrides.agentId ?? `agt_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return auditsSchemas.AuditChainVerifyRequest.parse(raw);
}
