/**
 * Routes for Delegation
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: delegations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createDelegationEdge, getDelegationEdge, listDelegationEdges } from "../handlers/delegation.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { DelegationEdgeCreateRequest } from "@agentfence/core/delegations/types";

// Fastify types are available globally
export async function delegationRoutes(fastify: FastifyInstance) {
  // POST /v1/delegations (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/delegations",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: DelegationEdgeCreateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDelegationsDependenciesForRequest();
        await createDelegationEdge(request, reply, deps);
      });
    }
  );


  // GET /v1/delegations (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/delegations",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDelegationsDependenciesForRequest();
        await listDelegationEdges(request, reply, deps);
      });
    }
  );


  // GET /v1/delegations/{delegationId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/delegations/:delegationId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { delegationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDelegationsDependenciesForRequest();
        await getDelegationEdge(request, reply, deps);
      });
    }
  );


}
