/**
 * Routes for Inheritance
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: delegations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getDelegationInheritance } from "../handlers/inheritance.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function inheritanceRoutes(fastify: FastifyInstance) {
  // GET /v1/delegations/{delegationId}/inheritance (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/delegations/:delegationId/inheritance",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { delegationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDelegationsDependenciesForRequest();
        await getDelegationInheritance(request, reply, deps);
      });
    }
  );


}
