/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: delegations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@agentfence/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@agentfence/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@agentfence/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _addOns from "./add-ons/index.js";
import * as _agents from "./agents/index.js";
import * as _audits from "./audits/index.js";
import * as _delegations from "./delegations/index.js";
import * as _identity from "./identity/index.js";
import * as _incidents from "./incidents/index.js";
import * as _killSwitch from "./kill-switch/index.js";
import * as _marketplaceAdapters from "./marketplace-adapters/index.js";
import * as _policies from "./policies/index.js";
import * as _reporting from "./reporting/index.js";

// Export as namespaces
export const addOns = _addOns;
export const agents = _agents;
export const audits = _audits;
export const delegations = _delegations;
export const identity = _identity;
export const incidents = _incidents;
export const killSwitch = _killSwitch;
export const marketplaceAdapters = _marketplaceAdapters;
export const policies = _policies;
export const reporting = _reporting;
