/**
 * Routes for Approve
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: add-ons
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { approveAddOnPackage } from "../handlers/approve.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { AddOnAttestRequest } from "@agentfence/core/add-ons/types";

// Fastify types are available globally
export async function approveRoutes(fastify: FastifyInstance) {
  // POST /v1/add-ons/{addOnId}/approve (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/add-ons/:addOnId/approve",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { addOnId: string }; Querystring: Record<string, string | string[] | undefined>; Body: AddOnAttestRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAddOnsDependenciesForRequest();
        await approveAddOnPackage(request, reply, deps);
      });
    }
  );


}
