/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: add-ons
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { addOnRoutes } from "./add-on.routes.js";
export { approveRoutes } from "./approve.routes.js";
export { revokeRoutes } from "./revoke.routes.js";
export { unloadRoutes } from "./unload.routes.js";
