/**
 * Repository interface for MarketplaceAdapter
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace-adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  MarketplaceAdapterEntity
} from "../models/marketplace-adapter.entity.js";
import type {
  ListMarketplaceAdaptersParams,
  MarketplaceAdapterCreateRequest
} from "../types/index.js";
/**
 * MarketplaceAdapterRepository Interface
 */
export interface MarketplaceAdapterRepository extends CreateReadRepository<MarketplaceAdapterEntity, MarketplaceAdapterCreateRequest, string, ListMarketplaceAdaptersParams> {

}
