/**
 * UnloadRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: add-ons
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * UnloadRepository Port
 *
 * DDD: Application port for unloadrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ForceUnloadAddOnPackageInput, ForceUnloadAddOnPackageOutput } from "../dto/unload.dto";
export interface UnloadRepository {
  forceUnloadAddOnPackage(input: ForceUnloadAddOnPackageInput): Promise<ForceUnloadAddOnPackageOutput>;
}

export type { ForceUnloadAddOnPackageInput, ForceUnloadAddOnPackageOutput } from "../dto/unload.dto";
