/**
 * RecordKillSwitchAck handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kill-switch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { recordKillSwitchAck } from "@agentfence/api-server/domains/kill-switch/handlers";
import type { KillSwitchDDDDependencies } from "@agentfence/api-server/domains/kill-switch";
import { createCreateAckRequest } from "@agentfence/factories/kill-switch";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@agentfence/tests/shared";
import { KILLSWITCH_USE_CASES } from "../__factories__/use-cases.js";

describe("RecordKillSwitchAck", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: KillSwitchDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<KillSwitchDDDDependencies>(
      KILLSWITCH_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateAckRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRecordKillSwitchAck, "execute").mockResolvedValue(useCaseResult);

    await recordKillSwitchAck(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRecordKillSwitchAck.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
