/**
 * ArmRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kill-switch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ArmRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ArmRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ArmRepository,
} from "@agentfence/services/kill-switch";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ArmRepositoryDdb } from "./arm-repository.ddb.js";

/**
 * ArmRepositoryAdapter
 *
 * Implements ArmRepository port for infrastructure layer.
 */
export class ArmRepositoryAdapter implements ArmRepository {
  private readonly ddb: ArmRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ArmRepositoryDdb(this.dynamoClient);
  }

  async armKillSwitch(input: Parameters<ArmRepository['armKillSwitch']>[0]): Promise<Awaited<ReturnType<ArmRepository['armKillSwitch']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.armKillSwitch(input);
  }
}
