/**
 * BlastRadiuRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kill-switch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BlastRadiuRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements BlastRadiuRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  BlastRadiuRepository,
} from "@agentfence/services/kill-switch";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { BlastRadiuRepositoryDdb } from "./blast-radiu-repository.ddb.js";

/**
 * BlastRadiuRepositoryAdapter
 *
 * Implements BlastRadiuRepository port for infrastructure layer.
 */
export class BlastRadiuRepositoryAdapter implements BlastRadiuRepository {
  private readonly ddb: BlastRadiuRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new BlastRadiuRepositoryDdb(this.dynamoClient);
  }

  async getKillSwitchBlastRadius(input: Parameters<BlastRadiuRepository['getKillSwitchBlastRadius']>[0]): Promise<Awaited<ReturnType<BlastRadiuRepository['getKillSwitchBlastRadius']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getKillSwitchBlastRadius(input);
  }
}
