/**
 * BlastRadiu DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kill-switch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BlastRadiu DTOs
 *
 * DDD: Application DTOs for BlastRadiu use cases.
 */

import type { GetKillSwitchBlastRadiusParams } from "@agentfence/core/kill-switch/types";

export type GetKillSwitchBlastRadiusInput = GetKillSwitchBlastRadiusParams;

export type GetKillSwitchBlastRadiusOutput = {};
