/**
 * Order DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kill-switch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Order DTOs
 *
 * DDD: Application DTOs for Order use cases.
 */

import type { GetKillSwitchOrderParams, KillSwitchOrderCreateRequest, ListKillSwitchOrdersParams } from "@agentfence/core/kill-switch/types";

export type ListKillSwitchOrdersInput = ListKillSwitchOrdersParams;

export type InvokeKillSwitchInput = KillSwitchOrderCreateRequest;

export type GetKillSwitchOrderInput = GetKillSwitchOrderParams;

export type ListKillSwitchOrdersOutput = {};

export type InvokeKillSwitchOutput = {};

export type GetKillSwitchOrderOutput = {};
