/**
 * AgentRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AgentRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AgentRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AgentRepository,
} from "@agentfence/services/agents";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AgentRepositoryDdb } from "./agent-repository.ddb.js";

/**
 * AgentRepositoryAdapter
 *
 * Implements AgentRepository port for infrastructure layer.
 */
export class AgentRepositoryAdapter implements AgentRepository {
  private readonly ddb: AgentRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AgentRepositoryDdb(this.dynamoClient);
  }

  async listAgents(input: Parameters<AgentRepository['listAgents']>[0]): Promise<Awaited<ReturnType<AgentRepository['listAgents']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAgents(input);
  }

  async registerAgent(input: Parameters<AgentRepository['registerAgent']>[0]): Promise<Awaited<ReturnType<AgentRepository['registerAgent']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerAgent(input);
  }

  async getAgent(input: Parameters<AgentRepository['getAgent']>[0]): Promise<Awaited<ReturnType<AgentRepository['getAgent']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getAgent(input);
  }

  async updateAgent(input: Parameters<AgentRepository['updateAgent']>[0]): Promise<Awaited<ReturnType<AgentRepository['updateAgent']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateAgent(input);
  }
}
