/**
 * MarketplaceIdRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MarketplaceIdRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements MarketplaceIdRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  MarketplaceIdRepository,
} from "@agentfence/services/agents";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { MarketplaceIdRepositoryDdb } from "./marketplace-id-repository.ddb.js";

/**
 * MarketplaceIdRepositoryAdapter
 *
 * Implements MarketplaceIdRepository port for infrastructure layer.
 */
export class MarketplaceIdRepositoryAdapter implements MarketplaceIdRepository {
  private readonly ddb: MarketplaceIdRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new MarketplaceIdRepositoryDdb(this.dynamoClient);
  }

  async mapAgentMarketplaceIds(input: Parameters<MarketplaceIdRepository['mapAgentMarketplaceIds']>[0]): Promise<Awaited<ReturnType<MarketplaceIdRepository['mapAgentMarketplaceIds']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.mapAgentMarketplaceIds(input);
  }
}
