/**
 * ShadowConflictRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ShadowConflictRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ShadowConflictRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ShadowConflictRepository,
} from "@agentfence/services/agents";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ShadowConflictRepositoryDdb } from "./shadow-conflict-repository.ddb.js";

/**
 * ShadowConflictRepositoryAdapter
 *
 * Implements ShadowConflictRepository port for infrastructure layer.
 */
export class ShadowConflictRepositoryAdapter implements ShadowConflictRepository {
  private readonly ddb: ShadowConflictRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ShadowConflictRepositoryDdb(this.dynamoClient);
  }

  async listShadowAgentConflicts(input: Parameters<ShadowConflictRepository['listShadowAgentConflicts']>[0]): Promise<Awaited<ReturnType<ShadowConflictRepository['listShadowAgentConflicts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listShadowAgentConflicts(input);
  }
}
