/**
 * Handlers for Exception
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PoliciesDomainModule } from "../dependencies/policies-ddd.dependencies.js";
import type { PolicyExceptionRequest } from "@agentfence/core/policies/types";
import type { GrantPolicyExceptionInput } from "@agentfence/services/policies";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/policies/exceptions
 * Operation: grantPolicyException
 */
export async function grantPolicyException(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: PolicyExceptionRequest }>,
  reply: FastifyReply,
  deps: PoliciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GrantPolicyExceptionInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.exceptions.get.execute(input);
  return reply.code(201).send(result);
}


