/**
 * Handlers for Policy
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PoliciesDomainModule } from "../dependencies/policies-ddd.dependencies.js";
import type { AutonomyPolicyCreateRequest, AutonomyPolicyUpdateRequest } from "@agentfence/core/policies/types";
import type { CreateAutonomyPolicyInput, GetAutonomyPolicyInput, ListAutonomyPoliciesInput, UpdateAutonomyPolicyInput } from "@agentfence/services/policies";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/policies
 * Operation: listAutonomyPolicies
 */
export async function listAutonomyPolicies(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], agentId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: PoliciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListAutonomyPoliciesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.policies.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/policies
 * Operation: createAutonomyPolicy
 */
export async function createAutonomyPolicy(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: AutonomyPolicyCreateRequest }>,
  reply: FastifyReply,
  deps: PoliciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateAutonomyPolicyInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.policies.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/policies/{policyId}
 * Operation: getAutonomyPolicy
 */
export async function getAutonomyPolicy(
  request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PoliciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetAutonomyPolicyInput = {
    policyId: request.params.policyId,
  };
  const result = await deps.useCases.policies.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/policies/{policyId}
 * Operation: updateAutonomyPolicy
 */
export async function updateAutonomyPolicy(
  request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: AutonomyPolicyUpdateRequest }>,
  reply: FastifyReply,
  deps: PoliciesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateAutonomyPolicyInput = {
    policyId: request.params.policyId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.policies.update.execute(input);
  return reply.code(200).send(result);
}


