/**
 * CreateException DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import { ulid } from "ulid";
import type { PolicyExceptionRequest } from "@agentfence/core/policies";
import { policiesSchemas } from "@agentfence/core/policies";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "pol";

export function createCreateExceptionRequest(overrides: Partial<PolicyExceptionRequest> = {}) {
  const raw = {
    actionType: overrides.actionType ?? faker.lorem.word(),
    agentId: overrides.agentId ?? `agt_${ulid().toLowerCase()}`,
    rationale: overrides.rationale ?? faker.lorem.word(),
    ...overrides,
  };

  return policiesSchemas.PolicyExceptionRequest.parse(raw);
}
