/**
 * MarketplaceAdapters Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace-adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const registerMarketplaceAdapter_Body = z
  .object({
    name: z.string().min(1),
    marketplace: z.enum(['fetch', 'singularitynet', 'internal']),
    webhookUrl: z.string().url().optional(),
  })
  .passthrough();
const acknowledgeHalt_Body = z
  .object({
    orderId: z.string().regex(/^ksw_[0-9A-HJKMNP-TV-Z]{26}$/),
    halted: z.boolean(),
    detail: z.string().optional(),
  })
  .passthrough();

export const schemas: any = {
  registerMarketplaceAdapter_Body,
  acknowledgeHalt_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/marketplace-adapters',
    alias: 'listMarketplaceAdapters',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().min(1).max(512).optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(100).optional().default(25),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  adapterId: z.string().regex(/^mkt_[0-9A-HJKMNP-TV-Z]{26}$/),
                  name: z.string(),
                  marketplace: z.enum(['fetch', 'singularitynet', 'internal']),
                  status: z.enum(['active', 'degraded', 'offline']),
                  webhookUrl: z.string().url().optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  lastHaltAckAt: z
                    .string()
                    .datetime({ offset: true })
                    .optional(),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/marketplace-adapters',
    alias: 'registerMarketplaceAdapter',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: registerMarketplaceAdapter_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            adapterId: z.string().regex(/^mkt_[0-9A-HJKMNP-TV-Z]{26}$/),
            name: z.string(),
            marketplace: z.enum(['fetch', 'singularitynet', 'internal']),
            status: z.enum(['active', 'degraded', 'offline']),
            webhookUrl: z.string().url().optional(),
            createdAt: z.string().datetime({ offset: true }),
            lastHaltAckAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/marketplace-adapters/:adapterId',
    alias: 'getMarketplaceAdapter',
    requestFormat: 'json',
    parameters: [
      {
        name: 'adapterId',
        type: 'Path',
        schema: z.string().regex(/^mkt_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            adapterId: z.string().regex(/^mkt_[0-9A-HJKMNP-TV-Z]{26}$/),
            name: z.string(),
            marketplace: z.enum(['fetch', 'singularitynet', 'internal']),
            status: z.enum(['active', 'degraded', 'offline']),
            webhookUrl: z.string().url().optional(),
            createdAt: z.string().datetime({ offset: true }),
            lastHaltAckAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/marketplace-adapters/:adapterId/halt-ack',
    alias: 'acknowledgeHalt',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: acknowledgeHalt_Body,
      },
      {
        name: 'adapterId',
        type: 'Path',
        schema: z.string().regex(/^mkt_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            adapterId: z.string().regex(/^mkt_[0-9A-HJKMNP-TV-Z]{26}$/),
            orderId: z.string().regex(/^ksw_[0-9A-HJKMNP-TV-Z]{26}$/),
            halted: z.boolean(),
            acknowledgedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/partner-attestations/:agentId',
    alias: 'verifyPartnerAttestation',
    requestFormat: 'json',
    parameters: [
      {
        name: 'agentId',
        type: 'Path',
        schema: z.string().regex(/^agt_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            agentId: z.string().regex(/^agt_[0-9A-HJKMNP-TV-Z]{26}$/),
            attested: z.boolean(),
            enterpriseId: z.string(),
            attestationStatus: z
              .enum(['unverified', 'attested', 'revoked'])
              .optional(),
            marketplaceIds: z.record(z.string()).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios('https://api.agentfence.local', endpoints);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
