/**
 * Audits Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const appendAuditEvent_Body = z
  .object({
    agentId: z.string().regex(/^agt_[0-9A-HJKMNP-TV-Z]{26}$/),
    actionType: z.string(),
    outcome: z.enum(['allowed', 'denied', 'exception']),
    modelProvenance: z.string().optional(),
    detailRef: z.string().optional(),
  })
  .passthrough();
const verifyAuditChain_Body = z
  .object({
    agentId: z.string().regex(/^agt_[0-9A-HJKMNP-TV-Z]{26}$/),
    fromEventId: z
      .string()
      .regex(/^aud_[0-9A-HJKMNP-TV-Z]{26}$/)
      .optional(),
    toEventId: z
      .string()
      .regex(/^aud_[0-9A-HJKMNP-TV-Z]{26}$/)
      .optional(),
  })
  .passthrough();

export const schemas: any = {
  appendAuditEvent_Body,
  verifyAuditChain_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/audits/events',
    alias: 'listAuditEvents',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().min(1).max(512).optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(100).optional().default(25),
      },
      {
        name: 'agentId',
        type: 'Query',
        schema: z
          .string()
          .regex(/^agt_[0-9A-HJKMNP-TV-Z]{26}$/)
          .optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  eventId: z.string().regex(/^aud_[0-9A-HJKMNP-TV-Z]{26}$/),
                  agentId: z.string().regex(/^agt_[0-9A-HJKMNP-TV-Z]{26}$/),
                  actionType: z.string(),
                  outcome: z.enum(['allowed', 'denied', 'exception']),
                  recordHash: z.string(),
                  previousHash: z.string().optional(),
                  modelProvenance: z.string().optional(),
                  detailRef: z.string().optional(),
                  occurredAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/audits/events',
    alias: 'appendAuditEvent',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: appendAuditEvent_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            eventId: z.string().regex(/^aud_[0-9A-HJKMNP-TV-Z]{26}$/),
            agentId: z.string().regex(/^agt_[0-9A-HJKMNP-TV-Z]{26}$/),
            actionType: z.string(),
            outcome: z.enum(['allowed', 'denied', 'exception']),
            recordHash: z.string(),
            previousHash: z.string().optional(),
            modelProvenance: z.string().optional(),
            detailRef: z.string().optional(),
            occurredAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/audits/events/:eventId',
    alias: 'getAuditEvent',
    requestFormat: 'json',
    parameters: [
      {
        name: 'eventId',
        type: 'Path',
        schema: z.string().regex(/^aud_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            eventId: z.string().regex(/^aud_[0-9A-HJKMNP-TV-Z]{26}$/),
            agentId: z.string().regex(/^agt_[0-9A-HJKMNP-TV-Z]{26}$/),
            actionType: z.string(),
            outcome: z.enum(['allowed', 'denied', 'exception']),
            recordHash: z.string(),
            previousHash: z.string().optional(),
            modelProvenance: z.string().optional(),
            detailRef: z.string().optional(),
            occurredAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/audits/verify-chain',
    alias: 'verifyAuditChain',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: verifyAuditChain_Body,
      },
    ],
    response: z
      .object({
        data: z
          .object({
            valid: z.boolean(),
            checkedCount: z.number().int(),
            brokenAtEventId: z
              .string()
              .regex(/^aud_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            detail: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios('https://api.agentfence.local', endpoints);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
