/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the agents domain.
 * Use these factories in tests to create test data.
 */

export { createCreateAgentRequest } from "./agent/dto/create-agent.dto.factory.js";
export { createCreateMarketplaceIdRequest } from "./marketplace-id/dto/create-marketplace-id.dto.factory.js";
export { createCreateRotateCredentialRequest } from "./rotate-credential/dto/create-rotate-credential.dto.factory.js";
export { createCreateSuspendRequest } from "./suspend/dto/create-suspend.dto.factory.js";
export { createShadowConflict } from "./shadow-conflict/entity/shadow-conflict.entity.factory.js";
export { createUpdateAgentRequest } from "./agent/dto/update-agent.dto.factory.js";
