/**
 * GetAgent DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetAgentParams } from "@agentfence/core/agents";

export function createGetAgentRequest(overrides: Partial<GetAgentParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
