/**
 * UpdateAgent DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { AgentUpdateRequest } from "@agentfence/core/agents";
import { agentsSchemas } from "@agentfence/core/agents";

export function createUpdateAgentRequest(overrides: Partial<AgentUpdateRequest> = {}) {
  const raw = {
    ...overrides,
  };

  return agentsSchemas.AgentUpdateRequest.parse(raw);
}
