/**
 * Handlers for Delegation
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: delegations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DelegationsDomainModule } from "../dependencies/delegations-ddd.dependencies.js";
import type { DelegationEdgeCreateRequest } from "@agentfence/core/delegations/types";
import type { CreateDelegationEdgeInput, GetDelegationEdgeInput, ListDelegationEdgesInput } from "@agentfence/services/delegations";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/delegations
 * Operation: listDelegationEdges
 */
export async function listDelegationEdges(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], parentAgentId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: DelegationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDelegationEdgesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.delegations.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/delegations
 * Operation: createDelegationEdge
 */
export async function createDelegationEdge(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: DelegationEdgeCreateRequest }>,
  reply: FastifyReply,
  deps: DelegationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateDelegationEdgeInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.delegations.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/delegations/{delegationId}
 * Operation: getDelegationEdge
 */
export async function getDelegationEdge(
  request: FastifyRequest<{ Params: { delegationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DelegationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDelegationEdgeInput = {
    delegationId: request.params.delegationId,
  };
  const result = await deps.useCases.delegations.get.execute(input);
  return reply.code(200).send(result);
}


