/**
 * Handlers for Inheritance
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: delegations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DelegationsDomainModule } from "../dependencies/delegations-ddd.dependencies.js";
import type { GetDelegationInheritanceInput } from "@agentfence/services/delegations";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/delegations/{delegationId}/inheritance
 * Operation: getDelegationInheritance
 */
export async function getDelegationInheritance(
  request: FastifyRequest<{ Params: { delegationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DelegationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDelegationInheritanceInput = {
    delegationId: request.params.delegationId,
  };
  const result = await deps.useCases.inheritances.get.execute(input);
  return reply.code(200).send(result);
}


