/**
 * Handlers for VerifyChain
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AuditsDomainModule } from "../dependencies/audits-ddd.dependencies.js";
import type { AuditChainVerifyRequest } from "@agentfence/core/audits/types";
import type { VerifyAuditChainInput } from "@agentfence/services/audits";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/audits/verify-chain
 * Operation: verifyAuditChain
 */
export async function verifyAuditChain(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: AuditChainVerifyRequest }>,
  reply: FastifyReply,
  deps: AuditsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: VerifyAuditChainInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.verifyChains.get.execute(input);
  return reply.code(200).send(result);
}


