/**
 * MarketplaceAdapterRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace-adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MarketplaceAdapterRepository Port
 *
 * DDD: Application port for marketplaceadapterrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetMarketplaceAdapterInput, GetMarketplaceAdapterOutput, ListMarketplaceAdaptersInput, ListMarketplaceAdaptersOutput, RegisterMarketplaceAdapterInput, RegisterMarketplaceAdapterOutput } from "../dto/marketplace-adapter.dto";
export interface MarketplaceAdapterRepository {
  listMarketplaceAdapters(input: ListMarketplaceAdaptersInput): Promise<ListMarketplaceAdaptersOutput>;
  registerMarketplaceAdapter(input: RegisterMarketplaceAdapterInput): Promise<RegisterMarketplaceAdapterOutput>;
  getMarketplaceAdapter(input: GetMarketplaceAdapterInput): Promise<GetMarketplaceAdapterOutput>;
}

export type { GetMarketplaceAdapterInput, GetMarketplaceAdapterOutput, ListMarketplaceAdaptersInput, ListMarketplaceAdaptersOutput, RegisterMarketplaceAdapterInput, RegisterMarketplaceAdapterOutput } from "../dto/marketplace-adapter.dto";
