/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kill-switch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { ackRoutes } from "./ack.routes.js";
export { armRoutes } from "./arm.routes.js";
export { blastRadiuRoutes } from "./blast-radiu.routes.js";
export { orderRoutes } from "./order.routes.js";
