/**
 * GetDelegationEdge handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: delegations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getDelegationEdge } from "@agentfence/api-server/domains/delegations/handlers";
import type { DelegationsDDDDependencies } from "@agentfence/api-server/domains/delegations";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@agentfence/tests/shared";
import { DELEGATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetDelegationEdge", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DelegationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DelegationsDDDDependencies>(
      DELEGATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetDelegationEdge, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { delegationId: entity.id };

    await getDelegationEdge(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetDelegationEdge.execute).toHaveBeenCalledWith(expect.objectContaining({ delegationId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { delegationId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetDelegationEdge, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getDelegationEdge(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
