/**
 * Routes for HaltAck
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace-adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { acknowledgeHalt } from "../handlers/halt-ack.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { HaltAckRequest } from "@agentfence/core/marketplace-adapters/types";

// Fastify types are available globally
export async function haltAckRoutes(fastify: FastifyInstance) {
  // POST /v1/marketplace-adapters/{adapterId}/halt-ack (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/marketplace-adapters/:adapterId/halt-ack",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { adapterId: string }; Querystring: Record<string, string | string[] | undefined>; Body: HaltAckRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMarketplaceAdaptersDependenciesForRequest();
        await acknowledgeHalt(request, reply, deps);
      });
    }
  );


}
