/**
 * Routes for PartnerAttestation
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace-adapters
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { verifyPartnerAttestation } from "../handlers/partner-attestation.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function partnerAttestationRoutes(fastify: FastifyInstance) {
  // GET /v1/partner-attestations/{agentId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/partner-attestations/:agentId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { agentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMarketplaceAdaptersDependenciesForRequest();
        await verifyPartnerAttestation(request, reply, deps);
      });
    }
  );


}
