/**
 * Routes for Agent
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getAgent, listAgents, registerAgent, updateAgent } from "../handlers/agent.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { AgentRegisterRequest, AgentUpdateRequest } from "@agentfence/core/agents/types";

// Fastify types are available globally
export async function agentRoutes(fastify: FastifyInstance) {
  // GET /v1/agents (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/agents",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAgentsDependenciesForRequest();
        await listAgents(request, reply, deps);
      });
    }
  );


  // POST /v1/agents (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/agents",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: AgentRegisterRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAgentsDependenciesForRequest();
        await registerAgent(request, reply, deps);
      });
    }
  );


  // GET /v1/agents/{agentId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/agents/:agentId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { agentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAgentsDependenciesForRequest();
        await getAgent(request, reply, deps);
      });
    }
  );


  // PATCH /v1/agents/{agentId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/agents/:agentId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { agentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: AgentUpdateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAgentsDependenciesForRequest();
        await updateAgent(request, reply, deps);
      });
    }
  );


}
