/**
 * Routes for MarketplaceId
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: agents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { mapAgentMarketplaceIds } from "../handlers/marketplace-id.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { AgentMarketplaceMapRequest } from "@agentfence/core/agents/types";

// Fastify types are available globally
export async function marketplaceIdRoutes(fastify: FastifyInstance) {
  // POST /v1/agents/{agentId}/marketplace-ids (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/agents/:agentId/marketplace-ids",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { agentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: AgentMarketplaceMapRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAgentsDependenciesForRequest();
        await mapAgentMarketplaceIds(request, reply, deps);
      });
    }
  );


}
